# permissions for end users to edit scalerpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: scalerpolicy-editor-role
rules:
- apiGroups:
  - autoscaling.my.domain
  resources:
  - scalerpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.my.domain
  resources:
  - scalerpolicies/status
  verbs:
  - get
